[NEW] Add gsheets

diff --git a/bin/sync-time b/bin/sync-time
--- a/bin/sync-time
+++ b/bin/sync-time
@@ -9,4 +9,13 @@ for PROJECT in $(jq -r '.[] | .id' app/data/timely_projects.json); do
   fi
 done
 
+for PROJECT in $(jq -r '.[] | .id' app/data/gsheets_projects.json); do
+  manage sync $@ -P gsheets -p ${PROJECT}; STATUS=$?
+
+  if [ $STATUS -ne 0 ]; then
+    echo "Sync exited with failures"
+    exit
+  fi
+done
+
 bin/sync-data
