Rename manager args and refactor time syncing

diff --git a/bin/sync-time b/bin/sync-time
--- a/bin/sync-time
+++ b/bin/sync-time
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash -uo pipefail
 
-# bin/store-users
-# bin/store-projects
-# bin/store-timely-events
-# bin/store-timely-tasks
-# bin/store-xero-events
-# bin/store-xero-tasks
+for PROJECT in $(jq -r '.[] | .id' app/data/timely_project_list.json); do
+  manage sync $@ -p${PROJECT}; STATUS=$?
 
-for PROJECT in $(jq -r 'to_entries[] | .key' app/data/timely_projects.json); do
-    manage sync -de 1 -p $PROJECT
+  if [ $STATUS -ne 0 ]; then
+    echo "Sync exited with failures"
+    exit
+  fi
 done
